github: your-github-username
patreon: your-patreon-username
open_collective: your-open-collective-username
ko_fi: your-ko-fi-username
tidelift: your-tidelift-username
community_bridge: your-community-bridge-username
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
otechie: your-otechie-username
custom:
  - url: https://your-custom-funding-platform.com
    title: Custom Funding
    - url: https://www.paypal.com/paypalme/your-paypal-username
    title: PayPal
  - url: https://cash.app/$your-cashapp-username
    title: Cash App
  - url: https://www.zellepay.com/your-zelle-info
    title: Zelle
