github: ibrogers0812  # Replace with your GitHub Sponsors profile when getting a Sponsor (none as of right now)
patreon: patreon-username
open_collective: open-collective-username
ko_fi: kofi-username
buymeacoffee: buymeacoffee-username
custom:
  - url: https://www.paypal.com/donate?hosted_button_id=YOUR-PAYPAL-BUTTON-ID
    title: Donate via PayPal
